##Pizza Place Sales

1) To upload Dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Pizza-Place-Sales.zip to Pizza-Place-Sales.zip

2) To extract the zip

In [ ]:
import zipfile

with zipfile.ZipFile("Pizza-Place-Sales.zip") as z:
    z.extractall("pizza_sales")

print("Extraction successful!")

Extraction successful!

In [ ]:
import os
os.listdir("pizza_sales/pizza_sales")

['pizza_types.csv', 'pizzas.csv', 'order_details.csv', 'orders.csv']

3) To load the CSV Files

In [ ]:
import pandas as pd

orders = pd.read_csv("pizza_sales/pizza_sales/orders.csv")
order_details = pd.read_csv("pizza_sales/pizza_sales/order_details.csv")
pizzas = pd.read_csv("pizza_sales/pizza_sales/pizzas.csv")
pizza_types = pd.read_csv("pizza_sales/pizza_sales/pizza_types.csv", encoding="latin1")

4) To merge All Tables

In [ ]:

sales_df = (
    order_details
    .merge(orders, on="order_id")
    .merge(pizzas, on="pizza_id")
    .merge(pizza_types, on="pizza_type_id")
)

sales_df.head()

,order_details_id,order_id,pizza_id,quantity,date,time,pizza_type_id,size,price,name,category,ingredients
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go..."
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,ital_supr,L,20.75,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
4,5,2,mexicana_m,1,2015-01-01,11:57:40,mexicana,M,16.00,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."

5) To Create Revenue Column

In [7]:
sales_df["revenue"] = sales_df["quantity"] * sales_df["price"]

6) Total Revenue

In [8]:
sales_df["revenue"].sum()

np.float64(817860.05)

7) Total Quantity Sold

In [9]:
sales_df["quantity"].sum()

np.int64(49574)

8)Total Orders

In [10]:
orders["order_id"].nunique()

21350

9)Number of Pizza Types

In [11]:
pizza_types["pizza_type_id"].nunique()

32

10) Average Price

In [19]:
pizzas["price"].mean()

np.float64(16.440625)

11) Peak Hours

In [13]:
sales_df["order_hour"] = pd.to_datetime(sales_df["time"]).dt.hour

sales_df.groupby("order_hour")["revenue"].sum().sort_values(ascending=False)

/tmp/ipython-input-3059927983.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales_df["order_hour"] = pd.to_datetime(sales_df["time"]).dt.hour

order_hour
12    111877.90
13    106065.70
18     89296.85
17     86237.45
19     72628.90
16     70055.40
14     59201.40
20     58215.40
15     52992.30
11     44935.80
21     42029.80
22     22815.15
23      1121.35
10       303.65
9         83.00
Name: revenue, dtype: float64

12)Sales by Day of Week

In [14]:
sales_df["order_date"] = pd.to_datetime(sales_df["date"])
sales_df["day"] = sales_df["order_date"].dt.day_name()

sales_df.groupby("day")["revenue"].sum().sort_values(ascending=False)

day
Friday       136073.90
Thursday     123528.50
Saturday     123182.40
Wednesday    114408.40
Tuesday      114133.80
Monday       107329.55
Sunday        99203.50
Name: revenue, dtype: float64

13)Top 5 Bestselling Pizzas

In [15]:
sales_df.groupby("name")["quantity"].sum().sort_values(ascending=False).head(5)

name
The Classic Deluxe Pizza      2453
The Barbecue Chicken Pizza    2432
The Hawaiian Pizza            2422
The Pepperoni Pizza           2418
The Thai Chicken Pizza        2371
Name: quantity, dtype: int64

16) Monthly Sales

In [16]:
sales_df["month"] = sales_df["order_date"].dt.month_name()

sales_df.groupby("month")["revenue"].sum()

month
April        68736.80
August       68278.25
December     64701.15
February     65159.60
January      69793.30
July         72557.90
June         68230.20
March        70397.10
May          71402.75
November     70395.35
October      64027.60
September    64180.05
Name: revenue, dtype: float64

17)Least Selling Pizzas

In [17]:
sales_df.groupby("name")["quantity"].sum().sort_values().head(5)

name
The Brie Carre Pizza         490
The Mediterranean Pizza      934
The Calabrese Pizza          937
The Spinach Supreme Pizza    950
The Soppressata Pizza        961
Name: quantity, dtype: int64